=== cmsong-shina/hpc015/examples/config_json_schema.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "type": "object",
  "properties": {
    "command-type": {
      "type": "string"
    },
    "speed": {
      "type": "string"
    },
    "recording-cycle": {
      "type": "integer"
    },
    "uploading-cycle": {
      "type": "integer"
    },
    "fixed-time-upload": {
      "type": "array",
      "items": [
        {
          "type": "object",
          "properties": {
            "enable": {
              "type": "boolean"
            },
            "upload-hour": {
              "type": "integer"
            },
            "upload-minutes": {
              "type": "integer"
            }
          },
          "required": [
            "enable",
            "upload-hour",
            "upload-minutes"
          ]
        },
        {
          "type": "object",
          "properties": {
            "enable": {
              "type": "boolean"
            },
            "upload-hour": {
              "type": "integer"
            },
            "upload-minutes": {
              "type": "integer"
            }
          },
          "required": [
            "enable",
            "upload-hour",
            "upload-minutes"
          ]
        },
        {
          "type": "object",
          "properties": {
            "enable": {
              "type": "boolean"
            },
            "upload-hour": {
              "type": "integer"
            },
            "upload-minutes": {
              "type": "integer"
            }
          },
          "required": [
            "enable",
            "upload-hour",
            "upload-minutes"
          ]
        },
        {
          "type": "object",
          "properties": {
            "enable": {
              "type": "boolean"
            },
            "upload-hour": {
              "type": "integer"
            },
            "upload-minutes": {
              "type": "integer"
            }
          },
          "required": [
            "enable",
            "upload-hour",
            "upload-minutes"
          ]
        }
      ]
    },
    "operation-mode": {
      "type": "string"
    },
    "display-mode": {
      "type": "string"
    },
    "system-time": {
      "type": "string"
    },
    "business-hour": {
      "type": "object",
      "properties": {
        "open-hour": {
          "type": "string"
        },
        "closed-hour": {
          "type": "string"
        }
      },
      "required": [
        "open-hour",
        "closed-hour"
      ]
    }
  },
  "required": [
    "command-type",
    "speed",
    "recording-cycle",
    "uploading-cycle",
    "fixed-time-upload",
    "operation-mode",
    "display-mode",
    "system-time",
    "business-hour"
  ]
}

=== cmsong-shina/hpc015/examples/config.json
{
    "command-type": "exclude-all",
    "speed": "low-speed",
    "recording-cycle": 0,
    "uploading-cycle": 0,
    "fixed-time-upload": [
        {
            "enable": true,
            "upload-hour": 0,
            "upload-minutes": 0
        },
        {
            "enable": true,
            "upload-hour": 0,
            "upload-minutes": 0
        },
        {
            "enable": true,
            "upload-hour": 0,
            "upload-minutes": 0
        },
        {
            "enable": false,
            "upload-hour": 0,
            "upload-minutes": 0
        }
    ],
    "operation-mode": "stand-alone",
    "display-mode": "none",
    "system-time": "2021-06-02 09:02:58",
    "business-hour": {
        "open-hour": "09:00",
        "closed-hour": "23:00"
    }
}
